---
title: "STATS 604 Project 4 Model Training"
author: "Ethan Schubert"
date: "2025-11-11"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
library(nnet)
library(mgcv)
```

### Models


### Train and Test sets
```{r}
# Source helper functions for models
source("src/models.R")

# Load metered data
load("data/processed/metered_clean.RData")

# Load temperature data
load("data/processed/open_meteo_historical_temp.RData")
meteo_temp = forecast_temp

# Create train and test sets for metered (load) data and temperature data
load_train = metered_clean %>% filter(date_ept < '2025-01-01')
temp_train = meteo_temp %>% filter(date_ept < '2025-01-01')
load_test = metered_clean %>% filter(date_ept >= '2025-01-01')
temp_test = meteo_temp %>% filter(date_ept >= '2025-01-01')
```

### Training
Train models for forecasting load on the power grid
```{r}
# Train models to forecast load on grid
train_mw = function(load_data, temp_data, zone, subset=NULL) {
  prepped = mw_prepdata(load_data, temp_data, zone)
  prepped_data = prepped[[1]]
  summary_vars = prepped[[2]]
  #prepped_data = prepped_data %>% 
  #  arrange(date_ept, hour24_ept) %>%
  #  mutate(mw = c(0,diff(mw)))
   # mutate(mw = (mw-min(mw))/(max(mw)-min(mw)))
  gm = gam(mw ~ dayofyear_ept
           + month_num_ept
           #+ old_mw
           + s(hour24_ept)
           + s(dayofyear_ept)
           + year_ept + weekday_ept 
           + tempF1  + tempF2  + tempF3  + tempF4  + tempF5 
           + tempF6  + tempF7  + tempF8  + tempF9  + tempF10
           + tempF11 + tempF12 + tempF0
           + tempF1_sq + tempF2_sq + tempF3_sq + tempF4_sq + tempF5_sq 
           + tempF6_sq + tempF7_sq + tempF8_sq + tempF9_sq + tempF10_sq
           + tempF11_sq + tempF12_sq + tempF0_sq
           + is_thanksgiving + is_blackfriday + isweekend,
           family=gaussian(), 
           data=prepped_data, 
           weights=NULL, subset=subset)
  
  return(list(gm, zone, summary_vars))
}
```

### Cross Validation
```{r}
# Cross validation
mses = matrix(nrow=29, ncol=5)
zones = unique(metered_clean$load_area)
for(z in 1:length(zones)) {
  zone = zones[z]
  j = 0
  for(i in unique(metered_clean$year_ept)) {
    j = j+1
    print(j)

    load_train = metered_clean %>% filter(year_ept != i)
    temp_train = meteo_temp %>% filter(year(date_ept) != i)
    if(i == 2025) { # Test on days 273 to 303 (extent of 2025 data)
      load_test = metered_clean %>% filter(year_ept == i, between(dayofyear_ept, 273, 303))
      temp_test = meteo_temp %>% filter(year(date_ept) == i, between(yday(date_ept), 273, 303))
      old_mw = load_train %>% filter(between(dayofyear_ept, 273, 303), load_area==zz) %>% 
      group_by(hourofyear_ept) %>%
      summarize(avg_mw = mean(mw)) %>% ungroup()
    } else {
      load_test = metered_clean %>% filter(year_ept == i, between(dayofyear_ept, 300, 330))
      temp_test = meteo_temp %>% filter(year(date_ept) == i, between(yday(date_ept), 300, 330))
      old_mw = load_train %>% filter(between(dayofyear_ept, 300, 330), load_area==zz) %>% 
      group_by(hourofyear_ept) %>%
      summarize(avg_mw = mean(mw)) %>% ungroup()
    }
    
    gm = train_mw(load_train, temp_train, zz)
    preds = predict_mw(gm[[1]], load_train, temp_train, load_test, temp_test, gm[[2]], gm[[3]])

    pred_join = preds %>% left_join(load_test, by=join_by(load_area, date_ept, hour24_ept, hour24_utc))
    mses[z,j] = mean((pred_join$predicted_mw - pred_join$mw.y)^2)
  }
}

zone_means = metered_clean %>% group_by(load_area) %>% 
  summarize(mw = mean(mw)) %>% select(mw) %>% unlist()

data.frame(load_area = zones, rmse = sqrt(rowMeans(mses, na.rm=T)), mw = zone_means) %>% 
  ggplot(aes(y = load_area, x = rmse/mw)) +
  geom_point()
```

### Training
```{r}
# Define final train/test split
load_train = metered_clean %>% filter(between(date_ept, as.Date('2021-01-01'), as.Date('2025-09-29')))
temp_train = meteo_temp %>% filter(between(date_ept, as.Date('2021-01-01'), as.Date('2025-09-29')))

# Store all models in single list
mw_models = list()
zones = unique(metered_clean$load_area)
for(i in 1:length(zones)) {
  mw_models[[i]] = train_mw(load_train, temp_train, zone=zones[i])
}

# Save models
save(mw_models, file="models/mw_models.RData")
```

### Testing
```{r}
load_test = metered_clean %>% filter(between(date_ept, as.Date('2025-09-30'), as.Date('2025-11-03')))
temp_test = meteo_temp %>% filter(between(date_ept, as.Date('2025-09-30'), as.Date('2025-11-03')))

zones = unique(metered_clean$load_area)
mses = vector(length=length(zones))
for(i in 1:length(zones)) {
  gm = mw_models[[i]]
  preds = predict_mw(gm[[1]], load_train, temp_train, load_test, temp_test, zone=gm[[2]], gm[[3]])
  pred_join = preds %>% left_join(load_test, by=join_by(load_area, date_ept, hour24_ept, hour24_utc))
  mses[i] = mean((pred_join$predicted_mw - pred_join$mw.y)^2)
}

zone_means = metered_clean %>% group_by(load_area) %>% 
  summarize(mw = mean(mw)) %>% select(mw) %>% unlist()

data.frame(load_area = zones, rmse = sqrt(mses), mw = zone_means) %>% 
  ggplot(aes(y = load_area, x = rmse)) +
  geom_point()

data.frame(load_area = zones, rmse = sqrt(mses), mw = zone_means) %>% 
  ggplot(aes(y = load_area, x = rmse/mw)) +
  geom_point()
```


Train models for predicting the peak hour of load on the grid
```{r}
train_ph = function(load_data, temp_data, zone, mw_preds=NULL) {
  prepped = ph_prepdata(load_data, temp_data, zone, preds=mw_preds)
  prepped_data = prepped[[1]]
  summary_vars = prepped[[2]]
  nn = nnet(factor(peakhour) ~ dayofyear_ept + weekday_ept + week_num_ept
            + year_ept + month_num_ept + day_num_ept + day_sq
            + tempF0_min + tempF1_min + tempF2_min + tempF3_min + tempF4_min + 
            + tempF5_min + tempF6_min + tempF7_min + tempF8_min + tempF9_min + 
            + tempF10_min + tempF11_min + tempF12_min 
            + tempF0_max + tempF1_max + tempF2_max + tempF3_max + tempF4_max + 
            + tempF5_max + tempF6_max + tempF7_max + tempF8_max + tempF9_max + 
            + tempF10_max + tempF11_max + tempF12_max
            + tempF1_sq_max + tempF2_sq_max + tempF3_sq_max 
            + tempF4_sq_max + tempF5_sq_max + tempF6_sq_max
            + tempF7_sq_max + tempF8_sq_max + tempF9_sq_max
            + tempF10_sq_max + tempF11_sq_max + tempF12_sq_max + tempF0_sq_max
            + tempF1_sq_min + tempF2_sq_min + tempF3_sq_min 
            + tempF4_sq_min + tempF5_sq_min + tempF6_sq_min
            + tempF7_sq_min + tempF8_sq_min + tempF9_sq_min
            + tempF10_sq_min + tempF11_sq_min + tempF12_sq_min + tempF0_sq_min,
           # + last_peakhour,
           # + max_mw + med_mw + min_mw + mean_mw,
            data=prepped_data, weights=NULL, size=10, maxit=1000, decay=1.2)
  
  return(list(nn, zone, summary_vars))
}
```

### Cross validation
```{r}
misclass = matrix(nrow=29, ncol=5)
zones = unique(metered_clean$load_area)

load("models/mw_models.RData")
set.seed(123028)
for(z in 1:length(zones)) {
  zone = zones[z]
  j = 0
  for(i in unique(metered_clean$year_ept)) {
    j = j+1
    print(j)

    load_train = metered_clean %>% filter(year_ept != i)
    temp_train = meteo_temp %>% filter(year(date_ept) != i)
    if(i == 2025) { # Test on days 273 to 303 (extent of 2025 data)
      load_test = metered_clean %>% filter(year_ept == i, between(dayofyear_ept, 273, 303))
      temp_test = meteo_temp %>% filter(year(date_ept) == i, between(yday(date_ept), 273, 303))
    } else {
      load_test = metered_clean %>% filter(year_ept == i, between(dayofyear_ept, 300, 330))
      temp_test = meteo_temp %>% filter(year(date_ept) == i, between(yday(date_ept), 300, 330))
    }
    
    zz = zone
    #gm = mw_models[[z]]
    #mw_fit = predict_mw(gm[[1]], load_train, temp_train, load_train, temp_train, gm[[2]], gm[[3]])
    #nn = train_ph(load_train, temp_train, zz, mw_preds=mw_fit$predicted_mw)
    #mw_preds = predict_mw(gm[[1]], load_train, temp_train, load_test, temp_test, gm[[2]], gm[[3]])
    #preds = predict_ph(nn[[1]], load_test, temp_test, nn[[2]], nn[[3]], mw_preds)
    
    nn = train_ph(load_train, temp_train, zz)
    preds = predict_ph(nn[[1]], load_test, temp_test, nn[[2]], nn[[3]])

    true_peaks = load_test %>% filter(load_area == nn[[2]]) %>% 
      group_by(date_ept) %>% 
      arrange(hour24_ept, .by_group=TRUE) %>% 
      summarize(peakhour = which.max(mw)%%24)
    
    classdiff = preds$predicted_ph - true_peaks$peakhour
    misclass[z,j] = mean(abs(classdiff) > 1)
  }
}

data.frame(load_area = zones, misclass = rowMeans(misclass), mw = zone_means) %>% 
  ggplot(aes(y = load_area, x = misclass)) +
  geom_point()
```

Training
```{r}
# Define final train/test split
load_train = metered_clean %>% filter(between(date_ept, as.Date('2021-01-01'), as.Date('2025-09-29')))
temp_train = meteo_temp %>% filter(between(date_ept, as.Date('2021-01-01'), as.Date('2025-09-29')))

# Store all models in single list
ph_models = list()
zones = unique(metered_clean$load_area)

set.seed(39238)
for(i in 1:length(zones)) {
  ph_models[[i]] = train_ph(load_train, temp_train, zones[i])
}

# Save models
save(ph_models, file="models/ph_models.RData")
```

### Testing
```{r}
load_test = metered_clean %>% filter(between(date_ept, as.Date('2025-09-30'), as.Date('2025-11-03')))
temp_test = meteo_temp %>% filter(between(date_ept, as.Date('2025-09-30'), as.Date('2025-11-03')))

zones = unique(metered_clean$load_area)
misclass = vector(length=length(zones))
for(i in 1:length(zones)) {
  nn = ph_models[[i]]
  preds = predict_ph(nn[[1]], load_test, temp_test, zone=nn[[2]], nn[[3]])
  
  true_peaks = load_test %>% filter(load_area == nn[[2]]) %>% 
      group_by(date_ept) %>% 
      arrange(hour24_ept, .by_group=TRUE) %>% 
      summarize(peakhour = which.max(mw)%%24)
  classdiff = preds$predicted_ph - true_peaks$peakhour
  misclass[i] = mean(abs(classdiff) > 1)
}

data.frame(load_area = zones, misclass = misclass) %>% 
  ggplot(aes(y = load_area, x = misclass)) +
  geom_point()
```

### Peak Day Model
Train models for predicting the peak day within the week
```{r}
train_pd = function(load_data, temp_data, zone, mw_preds=NULL, permute=F) {
  prepped = pd_prepdata(load_data, temp_data, zone, preds=mw_preds)
  prepped_data = prepped[[1]]
  summary_vars = prepped[[2]]
  if(permute) {
    n = nrow(prepped_data)
    px = sample(1:n, n, replace=T)
    prepped_data = prepped_data[px,]
  }
  nn = nnet(factor(is_peak_day_in_week) ~ dayofyear_ept + year_ept + weekday_ept
            + week_num_ept
            + tempF1 + tempF2 + tempF3 + tempF4 + tempF5 + tempF6
            + tempF7 + tempF8 + tempF9 + tempF10 + tempF11 + tempF12 + tempF0
            + tempF1_sq + tempF2_sq + tempF3_sq 
            + tempF4_sq + tempF5_sq + tempF6_sq
            + tempF7_sq + tempF8_sq + tempF9_sq
            + tempF10_sq + tempF11_sq + tempF12_sq + tempF0_sq
            + peak_in_day + med_mw + mean_mw + min_mw,
            data=prepped_data, weights=NULL, size=10, maxit=1000)
  
  return(list(nn, zone, summary_vars))
}
```

### Cross Validation
```{r}
load("models/mw_models.RData")

misclass = matrix(nrow=29, ncol=5)
zones = unique(metered_clean$load_area)
set.seed(253923)
for(z in 1:length(zones)) {
  zone = zones[z]
  j = 0
  for(i in unique(metered_clean$year_ept)) {
    j = j+1
    print(j)

    load_train = metered_clean %>% filter(year_ept != i)
    temp_train = meteo_temp %>% filter(year(date_ept) != i)
    if(i == 2025) { # Test on days 273 to 303 (extent of 2025 data)
      load_test = metered_clean %>% filter(year_ept == i, between(dayofyear_ept, 273, 303))
      temp_test = meteo_temp %>% filter(year(date_ept) == i, between(yday(date_ept), 273, 303))
    } else {
      load_test = metered_clean %>% filter(year_ept == i, between(dayofyear_ept, 300, 330))
      temp_test = meteo_temp %>% filter(year(date_ept) == i, between(yday(date_ept), 300, 330))
    }
    
    zz = zone
    gm = mw_models[[z]]
    mw_fit = predict_mw(gm[[1]], load_train, temp_train, load_train, temp_train, gm[[2]], gm[[3]])
    nn = train_pd(load_train, temp_train, zz, mw_preds=mw_fit$predicted_mw)
    
    
    mw_preds = predict_mw(gm[[1]], load_train, temp_train, load_test, temp_test, gm[[2]], gm[[3]])
    preds = predict_pd(nn[[1]], load_test, temp_test, nn[[2]], nn[[3]], mw_preds)

    true_peaks = load_test %>% filter(load_area == nn[[2]]) %>%
      select(date_ept, is_peak_day_in_week) %>% unique()
    
    classdiff = preds$predicted_pd - true_peaks$is_peak_day_in_week
    ii = which(classdiff < 0)
    classdiff[ii] = 4
    misclass[z,j] = mean(classdiff)
  }
}

data.frame(load_area = zones, misclass = rowMeans(misclass), mw = zone_means) %>% 
  ggplot(aes(y = load_area, x = misclass)) +
  geom_point()
```

### Training
```{r}
# Load mw models
load(file="models/mw_models.RData")

# Define final train/test split
load_train = metered_clean %>% filter(between(date_ept, as.Date('2021-01-01'), as.Date('2025-09-29')))
temp_train = meteo_temp %>% filter(between(date_ept, as.Date('2021-01-01'), as.Date('2025-09-29')))

# Store all models in single list
pd_models = list()
zones = unique(metered_clean$load_area)
set.seed(931812)
for(i in 1:length(zones)) {
  gm = mw_models[[i]]
  stopifnot(zones[i] == gm[[2]])
  mw_fit = predict_mw(gm[[1]], load_train, temp_train, load_train, temp_train, gm[[2]], gm[[3]])
  pd_models[[i]] = train_pd(load_train, temp_train, zone=zones[i], mw_fit$predicted_mw)
  #pd_models[[i]] = pd_ensemble(load_train, temp_train, zone=zones[i], mw_preds, n_models=5)
}

# Save models
save(pd_models, file="models/pd_models.RData")
```

### Testing
```{r}
misclass = vector(length=29)
for(i in 1:29) {
gm = mw_models[[i]]
nn = pd_models[[i]]
mw_preds = predict_mw(gm[[1]], load_train, temp_train, load_test, temp_test, gm[[2]], gm[[3]])
nn_preds = predict_pd(nn[[1]], load_test, temp_test, nn[[2]], nn[[3]], mw_preds)
#nn_preds = pd_ensemble_predict(nn, load_test, temp_test, mw_preds)
true_peaks = load_test %>% filter(load_area == gm[[2]]) %>%
  select(date_ept, is_peak_day_in_week) %>% unique()

nn_classdiff = nn_preds$predicted_pd - true_peaks$is_peak_day_in_week
#nn_classdiff = nn_preds - true_peaks$is_peak_day_in_week
ii = which(nn_classdiff < 0)
nn_classdiff[ii] = 4
misclass[i] = mean(nn_classdiff)
}

data.frame(load_area = zones, misclass = misclass) %>% 
  ggplot(aes(y = load_area, x = misclass)) +
  geom_point()
```
